Some changes

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -13,6 +13,6 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: "I will fail"
-        run: exit 1
+        run: exit 0  # Change to 'exit 1' to simulate failure
       - name: "Say goodbye"
         run: echo "Goodbye!"
