practice workflow

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -13,6 +13,8 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: "I will fail"
-        run: exit 0  # Change to 'exit 1' to simulate failure
+        run: |
+          echo "I will fail this job"
+          exit 1  # Change to 'exit 1' to simulate failure
       - name: "Say goodbye"
         run: echo "Goodbye!"
